// <auto-generated />
using System;
using Data.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(CiocouPostgresDbContext))]
    [Migration("20230514195333_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Service.CioccEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpirationDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date_time");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("guid");

                    b.Property<bool>("IsDone")
                        .HasColumnType("boolean")
                        .HasColumnName("is_done");

                    b.Property<string>("UserName1")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name1");

                    b.Property<string>("UserName2")
                        .HasColumnType("text")
                        .HasColumnName("user_name2");

                    b.Property<string>("Winner")
                        .HasColumnType("text")
                        .HasColumnName("winner");

                    b.HasKey("Id")
                        .HasName("pk_ciocc_events");

                    b.ToTable("ciocc_events", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
